### ISSUE TITLE
缺少QDN的文件夹

### ISSUE THREAD

**Issue by nfhe** [Crawford-fang/ROS_pytorch_RL#1]
Hi，大佬
@Crawford-fang 
非常感谢大佬可以公开自己的开源代码，我对于深度强化学习训练机器人非常感兴趣，我下载了您的代码，但是运行出现错误，如下：

`/home/he/miniconda3/envs/rostorch/bin/python3.7 /home/he/turtlebot_ws/src/ROS_pytorch_RL/DQN/DQN2.py
Traceback (most recent call last):
  File "/home/he/turtlebot_ws/src/ROS_pytorch_RL/DQN/DQN2.py", line 147, in <module>
    dqn = DQN()  # 令dqn=DQN类
  File "/home/he/turtlebot_ws/src/ROS_pytorch_RL/DQN/DQN2.py", line 78, in __init__
    checkpoint = torch.load("/home/ffd/QDN/model/" + str(self.load_ep) + "a.pt")
  File "/home/he/miniconda3/envs/rostorch/lib/python3.7/site-packages/torch/serialization.py", line 594, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/he/miniconda3/envs/rostorch/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/he/miniconda3/envs/rostorch/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/home/ffd/QDN/model/780a.pt'`

我个人觉得是缺少QDN这个文件夹，如果大佬看到了，希望可以上传自己的QDN文件夹。或者可以帮助一下我解决一下问题。
希望可以尽快收到您的回复，非常感谢！

**Comment by Crawford-fang** [comment]
你好，收到你问题了，你修改一下路径就行了，这只是一个文件夹的名字。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月6日(周一) 上午10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: [Crawford-fang/ROS_pytorch_RL] 缺少QDN的文件夹 (Issue #1)




 
Hi，大佬
 @Crawford-fang
 非常感谢大佬可以公开自己的开源代码，我对于深度强化学习训练机器人非常感兴趣，我下载了您的代码，但是运行出现错误，如下：
 
/home/he/miniconda3/envs/rostorch/bin/python3.7 /home/he/turtlebot_ws/src/ROS_pytorch_RL/DQN/DQN2.py Traceback (most recent call last): File "/home/he/turtlebot_ws/src/ROS_pytorch_RL/DQN/DQN2.py", line 147, in <module&gt; dqn = DQN()  # 令dqn=DQN类 File "/home/he/turtlebot_ws/src/ROS_pytorch_RL/DQN/DQN2.py", line 78, in __init__ checkpoint = torch.load("/home/ffd/QDN/model/" + str(self.load_ep) + "a.pt") File "/home/he/miniconda3/envs/rostorch/lib/python3.7/site-packages/torch/serialization.py", line 594, in load with _open_file_like(f, 'rb') as opened_file: File "/home/he/miniconda3/envs/rostorch/lib/python3.7/site-packages/torch/serialization.py", line 230, in _open_file_like return _open_file(name_or_buffer, mode) File "/home/he/miniconda3/envs/rostorch/lib/python3.7/site-packages/torch/serialization.py", line 211, in __init__ super(_open_file, self).__init__(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: '/home/ffd/QDN/model/780a.pt'
 
我个人觉得是缺少QDN这个文件夹，如果大佬看到了，希望可以上传自己的QDN文件夹。或者可以帮助一下我解决一下问题。
 希望可以尽快收到您的回复，非常感谢！
